import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import AdSense from "@/components/AdSense";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <AdSense pId="4912331234184158" />
      </head>
      <body>
        <Navbar />
        {children}
      </body>
    </html >
  );
}
